name: calculation

on:
    push:
        branches: [ "main" ]
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - name: node
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: calculations
              run: node index.js

